projects:
  AmplifyAndroid:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - app/src/main/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        graphQLApiId: rgfvmwiyfrbadk3mawhosob7gy
      endpoints:
        prod: >-
          https://geshuchzyffcrf5wpajjswr32a.appsync-api.us-west-2.amazonaws.com/graphql
